CREATE TABLE users
(
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email         VARCHAR(255)                            NOT NULL,
  name          VARCHAR(255)                            NOT NULL,
  date_of_birth DATE,
  created_at    TIMESTAMP,
  updated_at    TIMESTAMP,
  CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
  ADD CONSTRAINT uc_users_email UNIQUE (email);
