pull_request_rules:
  - name: Automatic PR merge
    conditions:
      - "#approved-reviews-by>=1"
      - check-success="Run Tests"
      - label!=do-not-merge
    actions:
      merge:
        method: squash